name: Teste Simples de CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Teste Hello World (Comando Shell)
        run: echo "Hello, GitHub Actions! O teste manual funcionou."

      - name: Instalar dependências e rodar testes
        run: |
          echo "npm install"
          echo "npm test --if-present"
  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Teste Hello World (Comando Shell)
        run: echo "Hello, GitHub Actions! O teste manual funcionou."

      - name: Instalar dependências e rodar testes
        run: |
          echo "npm install"
          echo "npm test --if-present"
